name: product_catalogue_flutter
description: A flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Assets
  cupertino_icons: ^1.0.2
  
  #State-Management
  provider: ^6.0.3

  #Network
  dio: ^4.0.6 

  #Cache
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/